### PR TITLE
Tests skeleton

### PR DESCRIPTION
**Pull request by MarioBlazek**
Before merge please do following:
- enable Travis CI
- enable Codecov
- enable Scrutinizer
- create proper release on Github

### CODE REVIEW

**Comment by MarioBlazek** [comment]
Ping @emodric @iherak

**Comment by iherak** [comment]
Waiting for feedback from one project before preparing a release.

**Comment by emodric** [comment]
Integrations activated, you can try and start the build.

**Comment by MarioBlazek** [comment]
@iherak you can create release from existing tag.

**Comment by MarioBlazek** [comment]
ping @iherak

**Comment by iherak** [comment]
thanks @MarioBlazek

**Pull request merged**
